IMDB/IMDB.Web/Areas/Admin/Controllers/UsersController.cs
using IMDB.Data.Models;
using IMDB.Web.Areas.Admin.Models;
using IMDB.Web.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace IMDB.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IUserManager<User> _userManager;
        private readonly int PAGE_SIZE = 1;

        [TempData]
        public string StatusMessage { get; set; }

        public UsersController(IUserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var indexViewModel = new IndexViewModel(_userManager.Users, 1, PAGE_SIZE);
            indexViewModel.StatusMessage = StatusMessage;

            return View(indexViewModel);
        }
        public IActionResult UserGrid(int? page)
        {
            var pagedUsers = _userManager.Users
                                         .Select(u => new UserViewModel(u))
                                         .ToPagedList(page ?? 1, PAGE_SIZE);
            return PartialView("_UserGrid", pagedUsers);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockUser(UserModalModelView input)
        {
            var user = _userManager.Users.Where(u => u.Id == input.ID).FirstOrDefault();
            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return this.RedirectToAction(nameof(Index));
            }

            var enableLockOutResult = await _userManager.SetLockoutEnabledAsync(user, true);
            if (!enableLockOutResult.Succeeded)
            {
                this.StatusMessage = "Error: Could enable the lockout on the user!";
                return this.RedirectToAction(nameof(Index));
            }
            var lockoutTimeResult = await _userManager.SetLockoutEndDateAsync(user, DateTime.Today.AddYears(10));
            if (!lockoutTimeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not add time to user's lockout!";
                return this.RedirectToAction(nameof(Index));
            }
            this.StatusMessage = "The user has been successfully locked for 10 years!";
            return this.RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnlockUser(UserModalModelView input)
        {
            var user = _userManager.Users.Where(u => u.Id == input.ID).FirstOrDefault();
            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return this.RedirectToAction(nameof(Index));
            }

            var lockoutTimeResult = await _userManager.SetLockoutEndDateAsync(user, DateTime.Now);
            if (!lockoutTimeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not add time to user's lockout!";
                return this.RedirectToAction(nameof(Index));
            }
            this.StatusMessage = "The user has been successfully unlocked!";
            return this.RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(UserModalModelView input)
        {
            var user = _userManager.Users.Where(u => u.Id == input.ID).FirstOrDefault();
            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return this.RedirectToAction(nameof(Index));
            }

            foreach (var validator in _userManager.PasswordValidators)
            {
                var result = await validator.ValidateAsync(_userManager.Instance, user, input.ConfirmPassword);
                if (!result.Succeeded)
                {
                    this.StatusMessage = $"Error: {string.Join(" ", result.Errors.Select(e => e.Description)).Replace(".", "!")}";
                    return this.RedirectToAction(nameof(Index));
                }
            }

            if (!ModelState.IsValid)
            {
                this.StatusMessage = "Error: Passwords do not match!";
                return this.RedirectToAction(nameof(Index));
            }

            var removeResult = await _userManager.RemovePasswordAsync(user);
            if (!removeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not remove the old password!";
                return this.RedirectToAction(nameof(Index));
            }
            var addPasswordResult = await _userManager.AddPasswordAsync(user, input.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not change the password!";
                return this.RedirectToAction(nameof(Index));
            }
            this.StatusMessage = "The user's password has been changed!";
            return this.RedirectToAction(nameof(Index));
        }
    }
}

IMDB/IMDB.Web/Controllers/ReviewController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IMDB.Data.Models;
using IMDB.Services.Contracts;
using IMDB.Services.Exceptions;
using IMDB.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace IMDB.Web.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewsServices reviewsServices;
        private readonly UserManager<User> _userManager;

        public ReviewController(IReviewsServices reviewsServices, UserManager<User> userManager)
        {
            this.reviewsServices = reviewsServices;
            this._userManager = userManager;
        }

        [HttpGet("[controller]/[action]/{id}")]
        public async Task<IActionResult> AllReviews(int id)
        {
            try
            {
				var reviewsRaw = await this.reviewsServices.ListMovieReviewsAsync(id);
                var reviewsViewModels = reviewsRaw
                              .OrderByDescending(rev => rev.ReviewScore)
                              .Select(r => new ReviewViewModel(r))
                              .ToList();
                reviewsViewModels.Select(rev => rev.MovieId == id);

                return View(reviewsViewModels);
            }
            catch (MovieNotFoundException)
            {
                return this.NotFound();
            }
            catch (ArgumentException)
            {
                return this.NotFound();
            }
        }
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReview(int id, string currentAction, string currentController)
        {           
           var deletedReview = await this.reviewsServices.DeleteReviewAsync(id);
            return RedirectToAction(currentAction, currentController, new { id = deletedReview.MovieID});
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RateReview(int id, double rate, string currentAction, string currentController)
        {            
            var userId = await _userManager.GetUserIdAsync(await _userManager.GetUserAsync(HttpContext.User));
            var ratedReview = await this.reviewsServices.RateReviewAsync(id, rate, userId);
            return RedirectToAction(currentAction, currentController, new { id = ratedReview.MovieID});
        }
    }
}

IMDB/IMDB.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IMDB.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-left">
                    <img src="~/images/logo1.png"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Movie" asp-action="Index">Movies</a></li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="Movie" asp-action="Create">Create</a></li>
                    }
                    <li><a asp-area="" asp-controller="Movie" asp-action="Search">Search</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - IMDB.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

IMDB/IMDB.Web/Views/Shared/_ReviewPartial.cshtml
@model ReviewViewModel

<div class="reviewUser">
    User: @Model.User | Review Rating: @Model.Score (@Model.NumberOfVotes votes)
    @{
        if (User.IsInRole("Administrator"))
        {
            <a class="btn btn-deleteReview" data-toggle="modal" data-target="#delete">Delete</a>
            <!-- Modal -->
            <div id="delete" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Are you sure to delete this review?</h4>
                        </div>
                        <div class="modal-body">
                            <p>You are about to delete this review, are you sure?</p>
                        </div>
                        <div class="modal-footer">
                            <form asp-area="" asp-controller="Review" asp-action="DeleteReview" method="post">
                                <input type="hidden" name="id" value="@Model.ReviewID" />
                                <input type="hidden" name="currentAction" , value="@Model.CurrentAction" />
                                <input type="hidden" name="currentController" value="@Model.CurrentController" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dropdown">
                <a class="btn btn-rateReview" style="margin-left: 0%">Rate Review</a>
                <div id="myDropdown" class="dropdown-content">
                    @{
                        for (int i = 1; i <= 10; i++)
                        {
                            <form asp-area="" asp-controller="Review" asp-action="RateReview" method="post">
                                <input type="hidden" name="id" value="@Model.ReviewID" />
                                <input type="hidden" name="rate" value="@i" />
                                <input type="hidden" name="currentAction" , value="@Model.CurrentAction" />
                                <input type="hidden" name="currentController" value="@Model.CurrentController" />
                                <button type="submit" class="rateSubmitButton"><span class="fa fa-star checked" id="a">@i</span></button>
                            </form>
                        }
                    }
                </div>
            </div>
        }
        else if (this.User.Identity.IsAuthenticated)
        {
            if (Model.User == this.User.Identity.Name)
            {
                <a class="btn btn-deleteReview" data-toggle="modal" data-target="#delete">Delete</a>
                <!-- Modal -->
                <div id="delete" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Are you sure to delete this review?</h4>
                            </div>
                            <div class="modal-body">
                                <p>You are about to delete this review, are you sure?</p>
                            </div>
                            <div class="modal-footer">
                                <form asp-area="" asp-controller="Review" asp-action="DeleteReview" method="post">
                                    <input type="hidden" name="id" value="@Model.ReviewID" />
                                    <input type="hidden" name="currentAction" , value="@Model.CurrentAction" />
                                    <input type="hidden" name="currentController" value="@Model.CurrentController" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn btn-rateReview" style="margin-left: 0%">Rate Review</a>
                    <div id="myDropdown" class="dropdown-content">
                        @{
                            for (int i = 1; i <= 10; i++)
                            {
                                <form asp-area="" asp-controller="Review" asp-action="RateReview" method="post">
                                    <input type="hidden" name="id" value="@Model.ReviewID" />
                                    <input type="hidden" name="rate" value="@i" />
                                    <input type="hidden" name="currentAction" value="@Model.CurrentAction" />
                                    <input type="hidden" name="currentController" value="@Model.CurrentController" />
                                    <button type="submit" class="rateSubmitButton"><span class="fa fa-star checked" id="a">@i</span></button>
                                </form>
                            }
                        }
                    </div>
                </div>

            }
            else
            {
                <div class="dropdown">
                    <a class="btn btn-rateReview" style="margin-left: 0%">Rate Review</a>
                    <div id="myDropdown" class="dropdown-content">
                        @{
                            for (int i = 1; i <= 10; i++)
                            {
                                <form asp-area="" asp-controller="Review" asp-action="RateReview" method="post">
                                    <input type="hidden" name="id" value="@Model.ReviewID" />
                                    <input type="hidden" name="rate" value="@i" />
                                    <input type="hidden" name="currentAction" value="@Model.CurrentAction" />
                                    <input type="hidden" name="currentController" value="@Model.CurrentController" />
                                    <button type="submit" class="rateSubmitButton"><span class="fa fa-star checked" id="a">@i</span></button>
                                </form>
                            }
                        }
                    </div>
                </div>
            }
        }
        else
        {
            <a class="btn btn-rateReview" data-toggle="modal" data-target="#rateReviewModal">Rate Review</a>
        }
    }
</div>
<p></p>
<p class="font-italic">@Model.Text</p>

IMDB/IMDB.Web/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}